# Generated by Django 5.0.1 on 2024-02-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
