# Generated by Django 5.0.1 on 2024-02-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_offer_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(default='Available in List library', max_length=30),
        ),
    ]
