# Generated by Django 5.0.1 on 2024-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_book_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(upload_to='img', width_field=20),
        ),
    ]
